# Generated by Django 3.1.13 on 2021-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memovocab', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=20)),
                ('meaning_vocab', models.CharField(max_length=200)),
                ('type_vocab', models.CharField(max_length=200)),
            ],
        ),
    ]
