# Generated by Django 3.1.13 on 2021-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memovocab', '0003_student_vocab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_all', models.CharField(choices=[('VE', 'Verb'), ('NO', 'Noun'), ('AD', 'Adj'), ('AV', 'Adv')], default='VE', max_length=2)),
            ],
        ),
    ]
